export const appEnv = {
  PRODUCTION: process.env.NEXT_PUBLIC_NODE_ENV === 'production',
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  IMG_PROXY_KEY: process.env.NEXT_PUBLIC_IMG_PROXY_KEY,
  IMG_PROXY_SALT: process.env.NEXT_PUBLIC_IMG_PROXY_SALT,
  IMG_PROXY_URL: process.env.NEXT_PUBLIC_IMG_PROXY_URL,
  API_COOKIE_DOMAIN: process.env.NEXT_PUBLIC_API_COOKIE_DOMAIN,
  AUTH_MODE_TYPE: process.env.NEXT_PUBLIC_AUTH_MODE_TYPE ?? '2',
  STUDIO_URL: process.env.NEXT_PUBLIC_STUDIO_URL ?? '/',
  VERSION_ID: process.env.NEXT_PUBLIC_VERSION_ID,
  LOCALIZE_URL: process.env.NEXT_PUBLIC_LOCALIZE_URL,
  METRICS_API_URL: process.env.NEXT_PUBLIC_METRICS_API_URL,
};
